### PR TITLE
make JsonFormatter work in Python 3.x

### PR DESCRIPTION
**Pull request by jimabramson**

### CODE REVIEW

**Comment by gpolaert** [comment]
Hi @jimabramson,
Thanks for the contribution. Can you explain in two words what's going wrong.

@lokoms Could you check and made some tests before merging the PR?

**Comment by jimabramson** [comment]
Hi @gpolaert,

Since Python 3.2 the [Formatter](https://docs.python.org/3.2/library/logging.html#logging.Formatter) interface changed slightly and that seems to be the cause of the problem.

In a (pyramid / py3.5) project using fileConfig, without this change, `_extra` is getting set to `%` which causes in line 25, in process_log_record:

```
AttributeError: 'str' object has no attribute 'items'
```

**Comment by jimabramson** [comment]
@gpolaert @lokoms just wondering if my explanation made sense?

**Comment by jimabramson** [comment]
@gpolaert thanks for merging this fix - any plans for a PyPI release with this update?

**Pull request merged**
